language: python
python:
    - 2.6
    - 2.7
install:
    - python setup.py install
script: nosetests
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --upgrade -r requirements/requirements26_dev.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --upgrade -r requirements/requirements27_dev.txt; fi
    - pip install codecov
after_success:
  - codecov
branches:
    only:
        - master
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
